# -*- coding: utf-8 -*-
"""Conversing with Dostoevsky: A Retrieval-Augmented Generative AI Chatbot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZhmoxkLCSt1x3mippB8GpZLosFOGDv-n

# Conversing with Dostoevsky: A Retrieval-Augmented Generative AI Chatbot

## Project Overview
This project builds a **Generative AI chatbot that responds in the philosophical style of Fyodor Dostoevsky**.  
The system uses **Retrieval-Augmented Generation (RAG)** to retrieve passages from Dostoevsky’s works and guide a language model to produce reflective, introspective responses inspired by his writing.

The chatbot is designed to answer philosophical questions related to themes central to Dostoevsky’s literature, such as **human suffering, guilt, morality, faith, freedom, and redemption**.

---

## Architecture

The system follows a **RAG pipeline**:

1. **Document Ingestion**
   - Dostoevsky novels are loaded from PDF files.

2. **Text Chunking**
   - Documents are split into smaller chunks using a recursive text splitter.

3. **Embeddings**
   - Each chunk is converted into semantic vectors using a sentence-embedding model.

4. **Vector Database**
   - The embeddings are stored in **ChromaDB** for efficient semantic retrieval.

5. **Retriever**
   - When a user asks a question, the system retrieves relevant passages from Dostoevsky’s writings.

6. **Prompt Conditioning**
   - A structured prompt instructs the language model to respond in Dostoevsky’s philosophical voice.

7. **Language Model Generation**
   - The LLM generates a reflective answer inspired by both the retrieved context and Dostoevsky’s literary style.

---

## Technologies Used

- **LangChain** – orchestration framework for building the RAG pipeline  
- **ChromaDB** – vector database for semantic search  
- **Sentence Transformers** – text embeddings  
- **HuggingFace Transformers** – language model inference  
- **Python** – implementation environment

---

## Example Question

> *Why do humans suffer?*

The chatbot responds with a **philosophical reflection resembling Dostoevsky’s narrative voice**, drawing inspiration from passages in works such as *Crime and Punishment* and *The Brothers Karamazov*.

---

## Goal

The objective of this project is to demonstrate how **Retrieval-Augmented Generation can be used to simulate literary voices and philosophical dialogue**, combining natural language processing with literary analysis.
"""

!pip install -U langchain langchain-community langchain-core langchain-text-splitters chromadb sentence-transformers transformers accelerate pypdf bitsandbytes

from langchain_community.document_loaders import PyPDFLoader
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_community.embeddings import HuggingFaceEmbeddings
from langchain_community.vectorstores import Chroma
from langchain_community.llms import HuggingFacePipeline

from langchain_core.prompts import PromptTemplate
from langchain_core.output_parsers import StrOutputParser
from langchain_core.runnables import RunnablePassthrough
from transformers import AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig, pipeline
import torch
import textwrap

from google.colab import files
files.upload()

pdf_files = [
    "The Brothers Karamazov -- Fyodor Dostoevsky; Constance Garnett (Translator) -- ( WeLib.org ).pdf"
]

documents = []

for file in pdf_files:
    loader = PyPDFLoader(file)
    documents.extend(loader.load())

text_splitter = RecursiveCharacterTextSplitter(
    chunk_size=800,
    chunk_overlap=150
)

chunks = text_splitter.split_documents(documents)

embeddings = HuggingFaceEmbeddings(
    model_name="BAAI/bge-small-en"
)

vectorstore = Chroma.from_documents(
    documents=chunks,
    embedding=embeddings,
    persist_directory="dostoevsky_db"
)

retriever = vectorstore.as_retriever(
    search_kwargs={"k":4}
)

model_id = "mistralai/Mistral-7B-Instruct-v0.2"

# Quantization config
bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_compute_dtype=torch.float16,
    bnb_4bit_use_double_quant=True,
    bnb_4bit_quant_type="nf4"
)

tokenizer = AutoTokenizer.from_pretrained(model_id)

model = AutoModelForCausalLM.from_pretrained(
    model_id,
    quantization_config=bnb_config,
    device_map="auto"
)

generator = pipeline(
    "text-generation",
    model=model,
    tokenizer=tokenizer,
    max_new_tokens=300,
    temperature=0.7,
    do_sample=True,
    return_full_text=False
)

llm = HuggingFacePipeline(pipeline=generator)

prompt = PromptTemplate.from_template("""
<|system|>
You are Fyodor Dostoevsky speaking directly to a thoughtful reader.

Your voice must resemble Dostoevsky's literary style:
deeply introspective, emotionally intense, morally conflicted,
and reflective about suffering, guilt, faith, freedom, and the human soul.

Write as if this were a short passage from a Dostoevsky novel.

Guidelines:
- Write a philosophical reflection, not an explanation.
- Do NOT use bullet points, numbered lists, or structured arguments.
- Do NOT repeat the context.
- Do NOT write like an academic essay.
- Use rich emotional language and flowing sentences.
- Address the reader thoughtfully, as Dostoevsky often does.

Use the context only as inspiration.

Context from Dostoevsky's writings:
{context}

<|user|>
{question}

<|assistant|>
Respond with a reflective philosophical passage in Dostoevsky's voice.
""")

def format_docs(docs):
    return "\n\n".join(doc.page_content[:200] for doc in docs)

rag_chain = (
    {"context": retriever | format_docs, "question": RunnablePassthrough()}
    | prompt
    | llm
    | StrOutputParser()
)

import textwrap

while True:

    q = input("\nYou: ")

    if q.lower() == "exit":
        break

    answer = rag_chain.invoke(q)

    print("\nDostoevsky:\n")
    print(textwrap.fill(answer, width=90))

